apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../../../upstream/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user

images:
  - name: gcr.io/ml-pipeline/api-server
    newName: 900100542891.dkr.ecr.us-east-2.amazonaws.com/artistml
    newTag: api-server-2.0.0-alpha.3-20230114

